### ISSUE TITLE
Walkthrough: typo on state classes

### ISSUE THREAD

**Issue by lynxnathan** [gilbox/css-bliss#11]
Hi! Thanks for sharing your model, this looks great!

I was going through the walkthrough and saw that your CSS example is missing a space between the state class and the module class.

```html
<body ng-class="{isLoggedIn:userIsLoggedIn}">
  <div class="Header">...</div>
  <div class="Hero">...</div>
  <div class="FeatureGrid">...</div>
</body>
```

```css
/* modules/_Header.scss */
.Header {
  ...
}
.isLoggedIn.Header {
  ...
}
```

`.isLoggedIn.Header` should be `.isLoggedIn .Header` (or the DOM elements must be have both classes).

If you want a PR for this or if I'm missing something, let me know! 

Thanks.

**Comment by gilbox** [comment]
Good catch! If you submit a PR I would be greatful ( ◠‿◠ )

**Comment by lynxnathan** [comment]
Submitted the PR! Let me know if I can help on something else. :smile_cat:
