### ISSUE TITLE
Siblings

### ISSUE THREAD

**Issue by drochag** [gilbox/css-bliss#14]
Hey Gil 😄 
what do you think about `+` ?

Is there a better way of doing this ? (assuming the sibling selector is needed)

```
.FlightLeg {
  &-row {
    & + & {
      // some styles
    }
  }
}
```

**Comment by gilbox** [comment]
I Dan, hope you're well!! Good question, but I don't have an opinion because it's been too long since I wrote proper css or scss.... everything in javascript (react inline styles, css-in-js etc) these days.

**Comment by drochag** [comment]
I'm great, I hope you too. No worries, just wondered if you had a preference for this.
Regards! =)
